---
title: "Monkeypox World Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
  runtime: shiny
resource_files:
- countries sf/World_Countries__Generalized_.shp
- countries sf/World_Countries_(Generalized).xml
- countries sf/World_Countries__Generalized_.cpg
- countries sf/World_Countries__Generalized_.dbf
- countries sf/World_Countries__Generalized_.prj
- countries sf/World_Countries__Generalized_.shx
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(readr)
library(tidyr)
library(ggplot2)
library(plotly)
library(tmap)
library(sf)
library(leaflet)
library(rsconnect)
mpx_country_case_dat_v2 <- read_csv("exported data/mpx_country_case_dat_v2.csv")
mpx_gbl_hospitalizations <- read_csv("exported data/mpx_gbl_hospitalizations.csv")
```



```{r map processing, include=FALSE}
# import shapefile
world_shp <- sf::st_read("countries sf/World_Countries__Generalized_.shp")

# sort country case date to latest 
mpx_global_latest <- mpx_country_case_dat_v2 %>%
  group_by(Country)%>%
  filter(Date_confirmation == max(Date_confirmation), Country != "World")%>%
  select(Country, Date_confirmation, cumulative_confirmed, cumulative_confirmed_suspected, cumulative_confirmed_per_1M, cumulative_confirmed_suspected_per_1M)

mpx_global_map <- merge(world_shp,
                        mpx_global_latest,
                        by.x = "COUNTRY", 
                        by.y = "Country", 
                        all = FALSE)


```


```{r value boxes, include=FALSE}
mpx_world <- mpx_country_case_dat_v2 %>%
  filter(Date_confirmation == max(Date_confirmation), Country == "World")
today_cumulative_confirmed = mpx_world$cumulative_confirmed[1]
today_cumulative_suspected = mpx_world$cumulative_suspected[1]
today_cumulative_confirmed_suspected = mpx_world$cumulative_confirmed_suspected[1]

```
Row 
---------------------------------------------------------------------------------------------

### Cumulative Confirmed Cases
```{r}
valueBox(today_cumulative_confirmed)
```

### Cumulative Suspected Cases
```{r}
valueBox(today_cumulative_suspected)
```

### Cumulative Confirmed and Suspected Cases
```{r}
valueBox(today_cumulative_confirmed_suspected)
```


Row { .tabset}
-----------------------------------------------------------------------

### Cumulative Confirmed Cases

```{r}
tmap_mode("view")
map1 <- tm_shape(mpx_global_map)+
  tm_polygons(col = "cumulative_confirmed")

map1
```

### Cumulative Cases & Suspected

```{r}

tmap_mode("view")
tm_shape(mpx_global_map)+
  tm_polygons(col = "cumulative_confirmed_suspected")
```


### Cumulative Confirmed per Million

```{r}
tmap_mode("view")
tm_shape(mpx_global_map)+
  tm_polygons(col = "cumulative_confirmed_per_1M")
```


### Cumulative Confirmed & Suspected per Million
```{r}
tmap_mode("view")
tm_shape(mpx_global_map)+
  tm_polygons(col = "cumulative_confirmed_suspected_per_1M")
```



Row {.tabset}
-----------------------------------------------------------------------

```{r filter all world data timeseries, include=FALSE}
mpx_world_ts <- mpx_country_case_dat_v2 %>%
  filter(Country == "World")
```


### Cumulative Case Trend
```{r}
plot_ly(mpx_world_ts, x = ~Date_confirmation, y = ~cumulative_confirmed, type = "scatter", mode = "lines", name = 'Cumulative Confirmed') %>%
  add_trace(y = ~cumulative_suspected, mode = 'lines', name = 'Cumulative Suspected')%>%
  add_trace(y = ~cumulative_confirmed_suspected, mode = "lines", name = "Cummulative Confirmed and Suspected")%>%
  layout(xaxis = list(title = "Date"), yaxis = list(title = "Cumulative Count"))
```

### World Daily Trend

```{r}
plot_ly(mpx_world_ts, x = ~Date_confirmation, y = ~confirmed, type = 'bar', name = 'Confirmed')%>%
  add_trace(y = ~suspected, name = 'Suspected')%>%
  layout(xaxis = list(title = 'Date'), yaxis = list(title = 'Daily Count'), barmode = 'stack')%>%
  add_trace(y = ~daily_confirmed_suspected_07d, type = "scatter", mode = 'lines', name = "7-day Rolling Average: Confirmed + Suspected")%>%
  add_trace(y = ~daily_confirmed_07d, type = "scatter", mode = 'lines', name = "7-day Rolling Average: Confirmed, only")
```

